using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Loacal_Market_Place.Models
{  [Table("ServiceInfo")]  
    public class RegisterService
    {
        [Key]  // This attribute specifies that the property is the primary key.
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]  // This attribute specifies that the value is generated by the database on insert.
        public int ShopId { get; set; }

        [Required(ErrorMessage = "Mobile No is required")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Invalid Mobile No")]
        public string MobileNo { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Password must be between 6 and 100 characters")]
        public string Password { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Service Name is required")]
        [StringLength(100, ErrorMessage = "Service Name can't exceed 100 characters")]
        public string ServiceName { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "First Name is required")]
        [RegularExpression(@"^[a-zA-Z\s]*$", ErrorMessage = "First Name can only contain alphabetic characters")]
        [StringLength(50, ErrorMessage = "First Name can't exceed 50 characters")]
        public string FirstName { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Last Name is required")]
        [RegularExpression(@"^[a-zA-Z\s]*$", ErrorMessage = "Last Name can only contain alphabetic characters")]
        [StringLength(50, ErrorMessage = "Last Name can't exceed 50 characters")]
        public string LastName { get; set; }


        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Service Category is required")]
        public string ServiceCategory { get; set; }

       
        [Required(ErrorMessage = "Service Amount is required")]
        [Range(1, double.MaxValue, ErrorMessage = "Service Amount must be greater than 0")]
        public decimal ServiceAmount { get; set; }

        [DefaultValue("10Am-5Pm")]
        public string JobTimings { get; set; }


        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Address is required")]
        [StringLength(200, ErrorMessage = "Address can't exceed 200 characters")]
        public string Address { get; set; }


        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "City is required")]
        [StringLength(100, ErrorMessage = "City can't exceed 100 characters")]
        public string City { get; set; }

        [Required(ErrorMessage = "Pin Code is required")]
        [RegularExpression(@"^\d{6}$", ErrorMessage = "Invalid Pin Code")]
        public string PinCode { get; set; }

        [DefaultValue("Unknown")]
        public string AdditionalInformation { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Adhar No is required")]
        [RegularExpression(@"^\d{12}$", ErrorMessage = "Invalid Adhar No")]
        public string AdharNo { get; set; }

        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "You must accept the terms and conditions")]
        public bool TermsAndConditionsAccepted { get; set; }
    }
}
