using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;

namespace Local_Market_Place_001.Models
{
       [Table("RegisterShop")]
    public class RegisterShop
    {

        [Key]  // Specifies that the property is the primary key.
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]  // Specifies that the value is generated by the database on insert.
        public int ShopAddId { get; set; }

        [DefaultValue("9854548382")]
        [Required(ErrorMessage = "Mobile number is required.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Invalid mobile number.")]
        public string MobileNo { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Password must be between 3 and 100 characters")]
        public string Password { get; set; }


        [Required(ErrorMessage = "Shop name is required.")]
        [StringLength(100, ErrorMessage = "Shop name cannot be longer than 100 characters.")]
        public string ShopName { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Address is required.")]
        public string Address { get; set; }

        [DefaultValue("9:00 AM - 11:00 PM")]
        public string ShopTimings { get; set; } = "9:00 AM - 9:00 PM"; // Default value

        [Required(ErrorMessage = "Shop category is required.")]
        public string ShopCategory { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "City is required.")]
        public string City { get; set; }

        [Required(ErrorMessage = "Pin/Zip Code is required.")]
        [RegularExpression(@"^\d{6}$", ErrorMessage = "Invalid Pin/Zip Code.")]
        public string PinCode { get; set; }

        [DefaultValue("R@gmail.com")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [DefaultValue("Unknown")]
        [Required(ErrorMessage = "Owner name is required.")]
        public string OwnerName { get; set; }

        [DefaultValue("9854548382")]
        [Required(ErrorMessage = "Owner mobile number is required.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Invalid mobile number.")]
        public string OwnerMobileNo { get; set; }

        [DefaultValue("123456789101")]
        [Required(ErrorMessage = "Aadhar number is required.")]
        [RegularExpression(@"^\d{12}$", ErrorMessage = "Invalid Aadhar number.")]
        public string AadharNo { get; set; }

        [DefaultValue(false)]
        [Required(ErrorMessage = "You must accept the terms and conditions.")]
        public bool TermsAndConditionsAccepted { get; set; } = false;
    }
}
