using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Local_Market_Place_001.Models
{
    [Table("UserLogin")]
    public class UserLogin
    {
        
        [Key]  // Specifies that the property is the primary key.
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]  // Specifies that the value is generated by the database on insert.
        public int UserLoginID { get; set; }

        [Required(ErrorMessage = "Mobile No is required.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Mobile No must be 10 digits.")]
        public string MobileNo { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters long.")]
        public string Password { get; set; }
    }
}
